export const SELECT_MENU = {
  DEPARTMENT: 'DEPARTMENT',
  USER: 'USER',
  EQUIPMENT: 'EQUIPMENT',
  EQUIPMENT_TYPE: 'EQUIPMENT_TYPE',
  MEDICAL_SUPPLIES: 'MEDICAL_SUPPLIES',
  MEDICAL_SUPPLIES_TYPE: 'MEDICAL_SUPPLIES_TYPE'
};

export const SELECT = {
  MENU: 'MENU',
  NOTIFICATION: 'NOTIFICATION',
  ACCOUNT: 'ACCOUNT'
};
